import type { MessageCatalog } from './types'

export default {
  // ---- nav ----
  'landing.nav.features': { en: 'Features', th: 'ฟีเจอร์', lo: 'ຄຸນສົມບັດ', vi: 'Tính năng', ms: 'Ciri-ciri' },
  'landing.nav.capabilities': { en: 'Capabilities', th: 'ความสามารถ', lo: 'ຄວາມສາມາດ', vi: 'Khả năng', ms: 'Keupayaan' },
  'landing.nav.login': { en: 'Log in', th: 'เข้าสู่ระบบ', lo: 'ເຂົ້າສູ່ລະບົບ', vi: 'Đăng nhập', ms: 'Log masuk' },
  'landing.nav.demo': { en: 'Request Demo', th: 'ขอทดลองใช้', lo: 'ຂໍທົດລອງໃຊ້', vi: 'Yêu cầu demo', ms: 'Minta Demo' },
  'landing.nav.menu': { en: 'Menu', th: 'เมนู', lo: 'ເມນູ', vi: 'Menu', ms: 'Menu' },
  'landing.nav.language': { en: 'Language', th: 'ภาษา', lo: 'ພາສາ', vi: 'Ngôn ngữ', ms: 'Bahasa' },

  // ---- hero ----
  'landing.hero.pre': { en: 'The smarter way to run your ', th: 'วิธีที่ชาญฉลาดกว่าในการบริหาร', lo: 'ວິທີທີ່ສະຫຼາດກວ່າໃນການບໍລິຫານ', vi: 'Cách thông minh hơn để vận hành ', ms: 'Cara lebih bijak untuk menguruskan ' },
  'landing.hero.highlight': { en: 'rental business', th: 'ธุรกิจเช่ายานพาหนะของคุณ', lo: 'ທຸລະກິດໃຫ້ເຊົ່າພາຫະນະຂອງທ່ານ', vi: 'việc kinh doanh cho thuê của bạn', ms: 'perniagaan penyewaan anda' },
  'landing.hero.body': { en: 'Fleet, lending, customers and revenue in one clean console, built for bike, scooter and car rental shops.', th: 'ยานพาหนะ การให้เช่า ลูกค้า และรายได้ รวมอยู่ในคอนโซลเดียวที่ใช้งานง่าย สร้างมาเพื่อร้านเช่าจักรยาน สกูตเตอร์ และรถยนต์', lo: 'ພາຫະນະ ການໃຫ້ເຊົ່າ ລູກຄ້າ ແລະ ລາຍຮັບ ລວມຢູ່ໃນຄອນໂຊນດຽວທີ່ໃຊ້ງ່າຍ ສ້າງມາເພື່ອຮ້ານເຊົ່າລົດຖີບ ສະກູດເຕີ ແລະ ລົດ', vi: 'Đội xe, cho thuê, khách hàng và doanh thu trong một bảng điều khiển gọn gàng, dành cho các cửa hàng cho thuê xe đạp, xe tay ga và ô tô.', ms: 'Armada, penyewaan, pelanggan dan hasil dalam satu konsol yang kemas, dibina untuk kedai sewa basikal, skuter dan kereta.' },
  'landing.hero.cta': { en: 'Request Demo', th: 'ขอทดลองใช้', lo: 'ຂໍທົດລອງໃຊ້', vi: 'Yêu cầu demo', ms: 'Minta Demo' },
  'landing.hero.dashboard_alt': { en: 'Rent Flow dashboard', th: 'แดชบอร์ด Rent Flow', lo: 'ແດຊບອດ Rent Flow', vi: 'Bảng điều khiển Rent Flow', ms: 'Papan pemuka Rent Flow' },
  'landing.hero.available_now': { en: 'Available now', th: 'ว่างตอนนี้', lo: 'ຫວ່າງຕອນນີ້', vi: 'Đang sẵn sàng', ms: 'Tersedia sekarang' },
  'landing.trust': { en: 'Trusted by rental businesses', th: 'ได้รับความไว้วางใจจากธุรกิจเช่า', lo: 'ໄດ້ຮັບຄວາມໄວ້ວາງໃຈຈາກທຸລະກິດໃຫ້ເຊົ່າ', vi: 'Được các doanh nghiệp cho thuê tin dùng', ms: 'Dipercayai oleh perniagaan penyewaan' },

  // ---- features ----
  'landing.features.title': { en: 'Everything your shop runs on, in one place', th: 'ทุกอย่างที่ร้านของคุณต้องใช้ ในที่เดียว', lo: 'ທຸກຢ່າງທີ່ຮ້ານຂອງທ່ານຕ້ອງໃຊ້ ໃນບ່ອນດຽວ', vi: 'Mọi thứ cửa hàng cần, gói gọn trong một nơi', ms: 'Segala yang diperlukan kedai anda, di satu tempat' },
  'landing.features.body': { en: 'From the first vehicle you add to the monthly revenue report, Rent Flow handles the whole operation.', th: 'ตั้งแต่ยานพาหนะคันแรกที่คุณเพิ่ม จนถึงรายงานรายได้ประจำเดือน Rent Flow ดูแลการทำงานทั้งหมดให้คุณ', lo: 'ຕັ້ງແຕ່ພາຫະນະຄັນທຳອິດທີ່ທ່ານເພີ່ມ ຈົນເຖິງລາຍງານລາຍຮັບປະຈຳເດືອນ Rent Flow ດູແລການດຳເນີນງານທັງໝົດໃຫ້ທ່ານ', vi: 'Từ chiếc xe đầu tiên bạn thêm vào đến báo cáo doanh thu hằng tháng, Rent Flow lo toàn bộ hoạt động.', ms: 'Dari kenderaan pertama yang anda tambah hingga laporan hasil bulanan, Rent Flow mengendalikan keseluruhan operasi.' },

  'landing.fleet.title': { en: 'Vehicle fleet management', th: 'จัดการยานพาหนะทั้งหมด', lo: 'ຈັດການພາຫະນະທັງໝົດ', vi: 'Quản lý đội xe', ms: 'Pengurusan armada kenderaan' },
  'landing.fleet.body': { en: 'Every bike, car and bicycle in one searchable list. Filter by category and status, then act in a single click.', th: 'มอเตอร์ไซค์ รถยนต์ และจักรยานทุกคัน อยู่ในรายการเดียวที่ค้นหาได้ กรองตามประเภทและสถานะ แล้วดำเนินการได้ในคลิกเดียว', lo: 'ລົດຈັກ ລົດ ແລະ ລົດຖີບທຸກຄັນ ຢູ່ໃນລາຍການດຽວທີ່ຄົ້ນຫາໄດ້ ກັ່ນຕອງຕາມປະເພດ ແລະ ສະຖານະ ແລ້ວດຳເນີນການໄດ້ໃນຄລິກດຽວ', vi: 'Mọi xe máy, ô tô và xe đạp trong một danh sách có thể tìm kiếm. Lọc theo loại và trạng thái, rồi thao tác chỉ với một cú nhấp.', ms: 'Setiap motosikal, kereta dan basikal dalam satu senarai yang boleh dicari. Tapis mengikut kategori dan status, kemudian bertindak dengan satu klik.' },
  'landing.fleet.p1': { en: 'Filter by Bike, Car or Bicycle', th: 'กรองตามมอเตอร์ไซค์ รถยนต์ หรือจักรยาน', lo: 'ກັ່ນຕອງຕາມລົດຈັກ ລົດ ຫຼື ລົດຖີບ', vi: 'Lọc theo xe máy, ô tô hoặc xe đạp', ms: 'Tapis mengikut Motosikal, Kereta atau Basikal' },
  'landing.fleet.p2': { en: 'Live Available / Lent / Reserved status', th: 'สถานะ ว่าง / ถูกเช่า / จองแล้ว แบบเรียลไทม์', lo: 'ສະຖານະ ຫວ່າງ / ຖືກເຊົ່າ / ຈອງແລ້ວ ແບບເວລາຈິງ', vi: 'Trạng thái Sẵn sàng / Đang cho thuê / Đã đặt trước theo thời gian thực', ms: 'Status Tersedia / Disewa / Ditempah secara langsung' },
  'landing.fleet.p3': { en: 'Quick-action menu on every vehicle', th: 'เมนูทางลัดในทุกคัน', lo: 'ເມນູລັດໃນທຸກຄັນ', vi: 'Menu thao tác nhanh trên mọi xe', ms: 'Menu tindakan pantas pada setiap kenderaan' },

  'landing.flow.title': { en: 'Step-by-step lending flow', th: 'ขั้นตอนการให้เช่าทีละขั้น', lo: 'ຂັ້ນຕອນການໃຫ້ເຊົ່າທີລະຂັ້ນ', vi: 'Quy trình cho thuê từng bước', ms: 'Aliran penyewaan langkah demi langkah' },
  'landing.flow.body': { en: 'A guided wizard takes staff from customer to vehicle to confirmation. Fast to learn, hard to get wrong.', th: 'ตัวช่วยแนะนำพาพนักงานไปตั้งแต่เลือกลูกค้า เลือกยานพาหนะ จนถึงยืนยัน เรียนรู้ง่าย ผิดพลาดยาก', lo: 'ຕົວຊ່ວຍນຳທາງພາພະນັກງານໄປຕັ້ງແຕ່ເລືອກລູກຄ້າ ເລືອກພາຫະນະ ຈົນເຖິງຢືນຢັນ ຮຽນຮູ້ງ່າຍ ຜິດພາດຍາກ', vi: 'Trình hướng dẫn dẫn nhân viên từ khách hàng đến xe rồi xác nhận. Dễ học, khó nhầm lẫn.', ms: 'Wizard berpandu membawa kakitangan dari pelanggan ke kenderaan hingga pengesahan. Mudah dipelajari, sukar tersilap.' },
  'landing.flow.p1': { en: 'Select customer, vehicle, then confirm', th: 'เลือกลูกค้า เลือกยานพาหนะ แล้วยืนยัน', lo: 'ເລືອກລູກຄ້າ ເລືອກພາຫະນະ ແລ້ວຢືນຢັນ', vi: 'Chọn khách hàng, chọn xe, rồi xác nhận', ms: 'Pilih pelanggan, kenderaan, kemudian sahkan' },
  'landing.flow.p2': { en: 'Only active customers surfaced', th: 'แสดงเฉพาะลูกค้าที่ใช้งานอยู่', lo: 'ສະແດງສະເພາະລູກຄ້າທີ່ໃຊ້ງານຢູ່', vi: 'Chỉ hiển thị khách hàng đang hoạt động', ms: 'Hanya pelanggan aktif dipaparkan' },
  'landing.flow.p3': { en: 'Clear progress at every step', th: 'เห็นความคืบหน้าชัดเจนในทุกขั้นตอน', lo: 'ເຫັນຄວາມຄືບໜ້າຊັດເຈນໃນທຸກຂັ້ນຕອນ', vi: 'Tiến độ rõ ràng ở mỗi bước', ms: 'Kemajuan jelas pada setiap langkah' },

  'landing.customers.title': { en: 'Customer management', th: 'จัดการลูกค้า', lo: 'ຈັດການລູກຄ້າ', vi: 'Quản lý khách hàng', ms: 'Pengurusan pelanggan' },
  'landing.customers.body': { en: 'A clean database of everyone who rents from you, with contact details, document tracking and live rental status.', th: 'ฐานข้อมูลลูกค้าที่เป็นระเบียบ พร้อมข้อมูลติดต่อ การติดตามเอกสาร และสถานะการเช่าแบบเรียลไทม์', lo: 'ຖານຂໍ້ມູນລູກຄ້າທີ່ເປັນລະບຽບ ພ້ອມຂໍ້ມູນຕິດຕໍ່ ການຕິດຕາມເອກະສານ ແລະ ສະຖານະການເຊົ່າແບບເວລາຈິງ', vi: 'Cơ sở dữ liệu gọn gàng về mọi người thuê xe của bạn, gồm thông tin liên hệ, theo dõi giấy tờ và trạng thái thuê trực tiếp.', ms: 'Pangkalan data kemas semua yang menyewa daripada anda, dengan butiran hubungan, penjejakan dokumen dan status sewa langsung.' },
  'landing.customers.p1': { en: 'Active / Renting / Inactive tracking', th: 'ติดตามสถานะ ใช้งานอยู่ / กำลังเช่า / ไม่ใช้งาน', lo: 'ຕິດຕາມສະຖານະ ໃຊ້ງານຢູ່ / ກຳລັງເຊົ່າ / ບໍ່ໃຊ້ງານ', vi: 'Theo dõi Hoạt động / Đang thuê / Không hoạt động', ms: 'Penjejakan Aktif / Menyewa / Tidak aktif' },
  'landing.customers.p2': { en: 'Contact info and documents on file', th: 'เก็บข้อมูลติดต่อและเอกสารไว้ในระบบ', lo: 'ເກັບຂໍ້ມູນຕິດຕໍ່ ແລະ ເອກະສານໄວ້ໃນລະບົບ', vi: 'Lưu thông tin liên hệ và giấy tờ', ms: 'Maklumat hubungan dan dokumen disimpan' },

  'landing.history.title': { en: 'Transaction history & export', th: 'ประวัติธุรกรรมและการส่งออก', lo: 'ປະຫວັດທຸລະກຳ ແລະ ການສົ່ງອອກ', vi: 'Lịch sử giao dịch & xuất dữ liệu', ms: 'Sejarah transaksi & eksport' },
  'landing.history.body': { en: 'Browse every transaction by month with duration and revenue per rental, then export the whole period to CSV in one click.', th: 'ดูทุกธุรกรรมแยกตามเดือน พร้อมระยะเวลาและรายได้ต่อการเช่า แล้วส่งออกทั้งช่วงเป็น CSV ในคลิกเดียว', lo: 'ເບິ່ງທຸກທຸລະກຳແຍກຕາມເດືອນ ພ້ອມໄລຍະເວລາ ແລະ ລາຍຮັບຕໍ່ການເຊົ່າ ແລ້ວສົ່ງອອກທັງຊ່ວງເປັນ CSV ໃນຄລິກດຽວ', vi: 'Xem mọi giao dịch theo tháng kèm thời lượng và doanh thu mỗi lượt thuê, rồi xuất cả giai đoạn ra CSV chỉ với một cú nhấp.', ms: 'Layari setiap transaksi mengikut bulan dengan tempoh dan hasil bagi setiap sewaan, kemudian eksport seluruh tempoh ke CSV dengan satu klik.' },
  'landing.history.p1': { en: 'Month-by-month history view', th: 'ดูประวัติทีละเดือน', lo: 'ເບິ່ງປະຫວັດທີລະເດືອນ', vi: 'Xem lịch sử theo từng tháng', ms: 'Paparan sejarah bulan demi bulan' },
  'landing.history.p2': { en: 'One-click CSV export', th: 'ส่งออก CSV ในคลิกเดียว', lo: 'ສົ່ງອອກ CSV ໃນຄລິກດຽວ', vi: 'Xuất CSV bằng một cú nhấp', ms: 'Eksport CSV satu klik' },

  // ---- capabilities ----
  'landing.cap.title': { en: 'More power as you grow', th: 'พลังที่มากขึ้นเมื่อธุรกิจเติบโต', lo: 'ພະລັງທີ່ຫຼາຍຂຶ້ນເມື່ອທຸລະກິດເຕີບໂຕ', vi: 'Thêm sức mạnh khi bạn phát triển', ms: 'Lebih banyak kuasa apabila anda berkembang' },
  'landing.cap.qr.title': { en: 'QR code scanner', th: 'สแกนคิวอาร์โค้ด', lo: 'ສະແກນ QR ໂຄ້ດ', vi: 'Quét mã QR', ms: 'Pengimbas kod QR' },
  'landing.cap.qr.body': { en: 'Scan a vehicle to pull up its record instantly. No typing, no lookup.', th: 'สแกนยานพาหนะเพื่อเรียกดูข้อมูลทันที ไม่ต้องพิมพ์ ไม่ต้องค้นหา', lo: 'ສະແກນພາຫະນະເພື່ອເອີ້ນເບິ່ງຂໍ້ມູນທັນທີ ບໍ່ຕ້ອງພິມ ບໍ່ຕ້ອງຄົ້ນຫາ', vi: 'Quét xe để mở ngay hồ sơ của xe. Không cần gõ, không cần tra cứu.', ms: 'Imbas kenderaan untuk memaparkan rekodnya serta-merta. Tanpa menaip, tanpa mencari.' },
  'landing.cap.store.title': { en: 'Multi-store management', th: 'จัดการหลายสาขา', lo: 'ຈັດການຫຼາຍສາຂາ', vi: 'Quản lý nhiều cửa hàng', ms: 'Pengurusan berbilang kedai' },
  'landing.cap.store.body': { en: 'Run every branch from a single admin console with one source of truth.', th: 'บริหารทุกสาขาจากคอนโซลผู้ดูแลเดียว ด้วยข้อมูลชุดเดียวกัน', lo: 'ບໍລິຫານທຸກສາຂາຈາກຄອນໂຊນຜູ້ດູແລດຽວ ດ້ວຍຂໍ້ມູນຊຸດດຽວກັນ', vi: 'Điều hành mọi chi nhánh từ một bảng quản trị với một nguồn dữ liệu duy nhất.', ms: 'Uruskan setiap cawangan dari satu konsol pentadbir dengan satu sumber data.' },
  'landing.cap.role.title': { en: 'Role-based access', th: 'สิทธิ์ตามบทบาท', lo: 'ສິດຕາມບົດບາດ', vi: 'Phân quyền theo vai trò', ms: 'Akses berasaskan peranan' },
  'landing.cap.role.body': { en: 'Owner, Branch Admin and Staff each see exactly what they should.', th: 'เจ้าของ ผู้ดูแลสาขา และพนักงาน เห็นเฉพาะสิ่งที่ควรเห็น', lo: 'ເຈົ້າຂອງ ຜູ້ດູແລສາຂາ ແລະ ພະນັກງານ ເຫັນສະເພາະສິ່ງທີ່ຄວນເຫັນ', vi: 'Chủ sở hữu, Quản trị chi nhánh và Nhân viên chỉ thấy đúng những gì họ cần.', ms: 'Pemilik, Pentadbir Cawangan dan Kakitangan masing-masing melihat apa yang sepatutnya.' },
  'landing.cap.currency.title': { en: 'Multi-currency support', th: 'รองรับหลายสกุลเงิน', lo: 'ຮອງຮັບຫຼາຍສະກຸນເງິນ', vi: 'Hỗ trợ đa tiền tệ', ms: 'Sokongan berbilang mata wang' },
  'landing.cap.currency.body': { en: 'Price and report in the currency each branch operates in.', th: 'ตั้งราคาและทำรายงานด้วยสกุลเงินที่แต่ละสาขาใช้งาน', lo: 'ຕັ້ງລາຄາ ແລະ ເຮັດລາຍງານດ້ວຍສະກຸນເງິນທີ່ແຕ່ລະສາຂາໃຊ້', vi: 'Định giá và báo cáo theo đồng tiền mà mỗi chi nhánh sử dụng.', ms: 'Tetapkan harga dan lapor dalam mata wang yang digunakan setiap cawangan.' },

  // ---- testimonials ----
  'landing.quote1.text': { en: 'We replaced three spreadsheets and a notebook with Rent Flow. Lending a scooter now takes under a minute and nothing falls through the cracks.', th: 'เราเปลี่ยนจากสเปรดชีตสามไฟล์และสมุดจดหนึ่งเล่มมาใช้ Rent Flow ตอนนี้ให้เช่าสกูตเตอร์ใช้เวลาไม่ถึงนาที และไม่มีอะไรตกหล่น', lo: 'ພວກເຮົາປ່ຽນຈາກສະເປຣດຊີດສາມໄຟລ໌ ແລະ ປຶ້ມບັນທຶກໜຶ່ງຫົວ ມາໃຊ້ Rent Flow ຕອນນີ້ການໃຫ້ເຊົ່າສະກູດເຕີໃຊ້ເວລາບໍ່ເຖິງນາທີ ແລະ ບໍ່ມີຫຍັງຕົກຫຼົ່ນ', vi: 'Chúng tôi đã thay ba bảng tính và một cuốn sổ bằng Rent Flow. Giờ cho thuê một chiếc xe tay ga mất chưa đến một phút và không có gì bị sót.', ms: 'Kami menggantikan tiga hamparan dan sebuah buku nota dengan Rent Flow. Menyewakan sebuah skuter kini mengambil masa kurang seminit dan tiada yang terlepas.' },
  'landing.quote1.role': { en: 'Owner · CityRide Scooters', th: 'เจ้าของ · CityRide Scooters', lo: 'ເຈົ້າຂອງ · CityRide Scooters', vi: 'Chủ sở hữu · CityRide Scooters', ms: 'Pemilik · CityRide Scooters' },
  'landing.quote2.text': { en: "The fleet view alone paid for itself. I can see what's available across both branches without calling anyone.", th: 'แค่หน้าภาพรวมยานพาหนะอย่างเดียวก็คุ้มค่าแล้ว ฉันดูได้ว่ามีคันไหนว่างในทั้งสองสาขาโดยไม่ต้องโทรหาใคร', lo: 'ພຽງແຕ່ໜ້າພາບລວມພາຫະນະກໍຄຸ້ມຄ່າແລ້ວ ຂ້ອຍເບິ່ງໄດ້ວ່າຄັນໃດຫວ່າງໃນທັງສອງສາຂາ ໂດຍບໍ່ຕ້ອງໂທຫາໃຜ', vi: 'Riêng màn hình đội xe đã đáng đồng tiền. Tôi xem được xe nào đang sẵn sàng ở cả hai chi nhánh mà không cần gọi cho ai.', ms: 'Paparan armada sahaja sudah berbaloi. Saya boleh melihat apa yang tersedia di kedua-dua cawangan tanpa menelefon sesiapa.' },
  'landing.quote2.role': { en: 'Branch Admin · Coastline Bikes', th: 'ผู้ดูแลสาขา · Coastline Bikes', lo: 'ຜູ້ດູແລສາຂາ · Coastline Bikes', vi: 'Quản trị chi nhánh · Coastline Bikes', ms: 'Pentadbir Cawangan · Coastline Bikes' },
  'landing.quote3.text': { en: "Month-end used to take a full afternoon. Now I export to CSV and I'm done before lunch.", th: 'สรุปสิ้นเดือนเคยใช้เวลาทั้งบ่าย ตอนนี้ส่งออกเป็น CSV แล้วเสร็จก่อนมื้อเที่ยง', lo: 'ການສະຫຼຸບທ້າຍເດືອນເຄີຍໃຊ້ເວລາທັງແລງ ຕອນນີ້ສົ່ງອອກເປັນ CSV ກໍແລ້ວກ່ອນຄ່ຳອາຫານທ່ຽງ', vi: 'Chốt sổ cuối tháng từng mất cả buổi chiều. Giờ tôi xuất CSV là xong trước bữa trưa.', ms: 'Penutupan akhir bulan dahulu mengambil masa sepetang. Kini saya eksport ke CSV dan siap sebelum makan tengah hari.' },
  'landing.quote3.role': { en: 'Owner · GreenWheel Rentals', th: 'เจ้าของ · GreenWheel Rentals', lo: 'ເຈົ້າຂອງ · GreenWheel Rentals', vi: 'Chủ sở hữu · GreenWheel Rentals', ms: 'Pemilik · GreenWheel Rentals' },

  // ---- CTA / footer ----
  'landing.cta.title': { en: 'Ready to streamline your rental operations?', th: 'พร้อมทำให้การดำเนินงานเช่าของคุณราบรื่นขึ้นหรือยัง', lo: 'ພ້ອມເຮັດໃຫ້ການດຳເນີນງານໃຫ້ເຊົ່າຂອງທ່ານລຽບງ່າຍຂຶ້ນແລ້ວບໍ', vi: 'Sẵn sàng tinh gọn hoạt động cho thuê của bạn?', ms: 'Bersedia untuk memperkemas operasi penyewaan anda?' },
  'landing.cta.body': { en: "See Rent Flow on your own fleet. We'll walk you through it.", th: 'ลองใช้ Rent Flow กับยานพาหนะของคุณเอง เราจะพาคุณทำความรู้จักทีละขั้น', lo: 'ລອງໃຊ້ Rent Flow ກັບພາຫະນະຂອງທ່ານເອງ ພວກເຮົາຈະພາທ່ານເຮັດຄວາມຮູ້ຈັກທີລະຂັ້ນ', vi: 'Xem Rent Flow trên chính đội xe của bạn. Chúng tôi sẽ hướng dẫn bạn.', ms: 'Lihat Rent Flow pada armada anda sendiri. Kami akan membimbing anda.' },
  'landing.cta.note': { en: 'No credit card required', th: 'ไม่ต้องใช้บัตรเครดิต', lo: 'ບໍ່ຕ້ອງໃຊ້ບັດເຄຣດິດ', vi: 'Không cần thẻ tín dụng', ms: 'Tidak perlu kad kredit' },
  'landing.footer.tagline': { en: 'The smarter way to run your rental business.', th: 'วิธีที่ชาญฉลาดกว่าในการบริหารธุรกิจเช่าของคุณ', lo: 'ວິທີທີ່ສະຫຼາດກວ່າໃນການບໍລິຫານທຸລະກິດໃຫ້ເຊົ່າຂອງທ່ານ', vi: 'Cách thông minh hơn để vận hành việc kinh doanh cho thuê của bạn.', ms: 'Cara lebih bijak untuk menguruskan perniagaan penyewaan anda.' },
  'landing.footer.product': { en: 'Product', th: 'ผลิตภัณฑ์', lo: 'ຜະລິດຕະພັນ', vi: 'Sản phẩm', ms: 'Produk' },
  'landing.footer.pricing': { en: 'Pricing', th: 'ราคา', lo: 'ລາຄາ', vi: 'Bảng giá', ms: 'Harga' },
  'landing.footer.coming_soon': { en: '(coming soon)', th: '(เร็วๆ นี้)', lo: '(ເຮັວໆ ນີ້)', vi: '(sắp ra mắt)', ms: '(akan datang)' },
  'landing.footer.company': { en: 'Company', th: 'บริษัท', lo: 'ບໍລິສັດ', vi: 'Công ty', ms: 'Syarikat' },
  'landing.footer.contact': { en: 'Contact', th: 'ติดต่อ', lo: 'ຕິດຕໍ່', vi: 'Liên hệ', ms: 'Hubungi' },
  'landing.footer.rights': { en: '© 2026 Rent Flow. All rights reserved.', th: '© 2026 Rent Flow สงวนลิขสิทธิ์', lo: '© 2026 Rent Flow ສະຫງວນລິຂະສິດ', vi: '© 2026 Rent Flow. Bảo lưu mọi quyền.', ms: '© 2026 Rent Flow. Hak cipta terpelihara.' },
  'landing.footer.built_for': { en: 'Built for rental shops worldwide', th: 'สร้างมาเพื่อร้านเช่าทั่วโลก', lo: 'ສ້າງມາເພື່ອຮ້ານເຊົ່າທົ່ວໂລກ', vi: 'Dành cho các cửa hàng cho thuê trên toàn thế giới', ms: 'Dibina untuk kedai sewa di seluruh dunia' }
} satisfies MessageCatalog
